Repository redacademy/STCSummer2019, pull requests merged in 2019-09, with the labels that each got.

#17 Add navigation stack dependencies
  client/package.json
  client/yarn.lock
  server/yarn.lock
Labels: enhancement

#18 Add react navigation tab dependencies
  client/package.json
  client/yarn.lock
Labels: enhancement

#19 Add link for react-native-reanimation
  .gitignore
  client/android/app/build.gradle
  client/android/app/src/main/java/com/stcsummer2019/MainApplication.java
  client/android/settings.gradle
  client/ios/Podfile
  client/ios/Podfile.lock
  client/package.json
  client/yarn.lock
Labels: enhancement

#22 Ad feature navigation
  client/App.js
  client/index.js
  client/js/App.js
  client/js/components/FilterItemList/FilterItemList.js
  client/js/components/FilterItemList/FilterItemListContainer.js
  client/js/components/FilterItemList/index.js
  client/js/components/FilterItemList/styles.js
  client/js/components/StoreList/StoreList.js
  client/js/components/StoreList/StoreListContainer.js
  client/js/components/StoreList/index.js
  client/js/components/StoreList/styles.js
  client/js/navigation/NavigationLayout.js
  client/js/navigation/RootStackNavigator.js
  client/js/navigation/config.js
  client/js/screens/Brand/Brand.js
  client/js/screens/Brand/BrandContainer.js
  client/js/screens/Brand/index.js
  client/js/screens/Brand/styles.js
  client/js/screens/Browse/Browse.js
  client/js/screens/Browse/BrowseContainer.js
  client/js/screens/Browse/index.js
  client/js/screens/Browse/styles.js
  client/js/screens/Filter/Filter.js
  client/js/screens/Filter/FilterContainer.js
  client/js/screens/Filter/index.js
  client/js/screens/Filter/styles.js
  client/js/screens/ForYou/ForYou.js
  client/js/screens/ForYou/ForYouContainer.js
  client/js/screens/ForYou/index.js
  client/js/screens/ForYou/styles.js
  client/js/screens/Item/Item.js
  client/js/screens/Item/ItemContainer.js
  client/js/screens/Item/index.js
  client/js/screens/Item/styles.js
  client/js/screens/ItemsPage/ItemsPage.js
  client/js/screens/ItemsPage/ItemsPageContainer.js
  client/js/screens/ItemsPage/index.js
  client/js/screens/ItemsPage/styles.js
  client/js/screens/Profile/Profile.js
  client/js/screens/Profile/ProfileContainer.js
  client/js/screens/Profile/index.js
  client/js/screens/Profile/styles.js
  client/js/screens/Sale/Sale.js
  client/js/screens/Sale/SaleContainer.js
  client/js/screens/Sale/index.js
  client/js/screens/Sale/styles.js
  client/js/screens/Store/Store.js
  client/js/screens/Store/StoreContainer.js
  client/js/screens/Store/index.js
  client/js/screens/Store/styles.js
  client/js/screens/StoresBrands/StoresBrands.js
  client/js/screens/StoresBrands/StoresBrandsContainer.js
  client/js/screens/StoresBrands/index.js
  client/js/screens/StoresBrands/styles.js
Labels: enhancement

#25 Yy createbrowsescreen
  client/js/assets/accessories.png
  client/js/assets/bags.png
  client/js/assets/clothing.png
  client/js/assets/fonts/Lato-Black.ttf
  client/js/assets/fonts/Lato-BlackItalic.ttf
  client/js/assets/fonts/Lato-Bold.ttf
  client/js/assets/fonts/Lato-BoldItalic.ttf
  client/js/assets/fonts/Lato-Hairline.ttf
  client/js/assets/fonts/Lato-HairlineItalic.ttf
  client/js/assets/fonts/Lato-Italic.ttf
  client/js/assets/fonts/Lato-Light.ttf
  client/js/assets/fonts/Lato-LightItalic.ttf
  client/js/assets/fonts/Lato-Regular.ttf
  client/js/assets/shoes.png
  client/js/screens/Browse/Browse.js
  client/js/screens/Browse/BrowseContainer.js
  client/js/screens/Browse/styles.js
Labels: enhancement

#31 Yy feature create global styling
  client/js/assets/fonts/Lato/Lato-Black.ttf
  client/js/assets/fonts/Lato/Lato-BlackItalic.ttf
  client/js/assets/fonts/Lato/Lato-Bold.ttf
  client/js/assets/fonts/Lato/Lato-BoldItalic.ttf
  client/js/assets/fonts/Lato/Lato-Hairline.ttf
  client/js/assets/fonts/Lato/Lato-HairlineItalic.ttf
  client/js/assets/fonts/Lato/Lato-Italic.ttf
  client/js/assets/fonts/Lato/Lato-Light.ttf
  client/js/assets/fonts/Lato/Lato-LightItalic.ttf
  client/js/assets/fonts/Lato/Lato-Regular.ttf
  client/js/assets/fonts/Lato/Montserrat-Light.ttf
  client/js/config/styles.js
  client/js/screens/Browse/styles.js
  client/react-native.config.js
Labels: enhancement

#48 fix user schema
  server/types.graphql
Labels: bug

#47 Ad feature storecard
  client/js/assets/icons/back-active3x.png
  client/js/assets/icons/back-inactive3x.png
  client/js/assets/icons/for-you-active.png
  client/js/assets/icons/for-you-active3x.png
  client/js/assets/icons/for-you-inactive.png
  client/js/assets/icons/for-you-inactive3x.png
  client/js/assets/icons/profile-active.png
  client/js/assets/icons/profile-active3x.png
  client/js/assets/icons/profile-inactive.png
  client/js/assets/icons/profile-inactive3x.png
  client/js/assets/icons/sales-active.png
  client/js/assets/icons/sales-active3x.png
  client/js/assets/icons/sales-inactive.png
  client/js/assets/icons/sales-inactive3x.png
  client/js/assets/icons/stc-active.png
  client/js/assets/icons/stc-active3x.png
  client/js/assets/icons/stc-inactive.png
  client/js/assets/icons/stc-inactive3x.png
  client/js/assets/icons/stores-brands-active.png
  client/js/assets/icons/stores-brands-active3x.png
  client/js/assets/icons/stores-brands-inactive.png
  client/js/assets/icons/stores-brands-inactive3x.png
  client/js/assets/images/accessories.png
  client/js/assets/images/bags.png
  client/js/assets/images/clothing.png
  client/js/assets/images/shoes.png
  client/js/components/StoreCard/StoreCard.js
  client/js/components/StoreCard/index.js
  client/js/components/StoreCard/styles.js
  client/js/navigation/NavigationLayout.js
  client/js/navigation/config.js
  client/js/navigation/styles.js
  client/js/screens/Browse/Browse.js
  client/js/screens/Browse/styles.js
Labels: enhancement

#46 Sd feature data modelling
  client/android/app/src/main/assets/fonts/Lato-Black.ttf
  client/android/app/src/main/assets/fonts/Lato-BlackItalic.ttf
  client/android/app/src/main/assets/fonts/Lato-Bold.ttf
  client/android/app/src/main/assets/fonts/Lato-BoldItalic.ttf
  client/android/app/src/main/assets/fonts/Lato-Hairline.ttf
  client/android/app/src/main/assets/fonts/Lato-HairlineItalic.ttf
  client/android/app/src/main/assets/fonts/Lato-Italic.ttf
  client/android/app/src/main/assets/fonts/Lato-Light.ttf
  client/android/app/src/main/assets/fonts/Lato-LightItalic.ttf
  client/android/app/src/main/assets/fonts/Lato-Regular.ttf
  client/android/app/src/main/assets/fonts/Montserrat-Light.ttf
  client/ios/STCSummer2019.xcodeproj/project.pbxproj
  client/ios/STCSummer2019/Info.plist
  client/js/screens/Browse/styles.js
  server/types.graphql
Labels: enhancement

#49 Vs feature faved context
  client/js/App.js
  client/js/components/StoreCard/StoreCard.js
  client/js/config/models/faved.js
  client/js/config/models/favedBrands.js
  client/js/config/models/favedItems.js
  client/js/config/models/favedStores.js
  client/js/context/FaveBrandsContext/FaveBrandsContext.js
  client/js/context/FaveBrandsContext/index.js
  client/js/context/FaveItemsContext/FaveItemsContext.js
  client/js/context/FaveItemsContext/index.js
  client/js/context/FaveStoresContext/FaveStoresContext.js
  client/js/context/FaveStoresContext/index.js
  client/js/screens/Brand/BrandContainer.js
  client/js/screens/Browse/styles.js
  client/js/screens/StoresBrands/StoresBrands.js
  client/js/screens/StoresBrands/StoresBrandsContainer.js
  client/react-native.config.js
Labels: enhancement

#50 Vs feature stores brands screen
  client/js/components/StoreCard/StoreCard.js
  client/js/config/models/authentication.js
  client/js/config/styles.js
  client/js/navigation/NavigationLayout.js
  client/js/screens/Brand/Brand.js
  client/js/screens/Brand/BrandContainer.js
  client/js/screens/Brands/Brands.js
  client/js/screens/Brands/BrandsContainer.js
  client/js/screens/Brands/index.js
  client/js/screens/Brands/styles.js
  client/js/screens/Profile/Profile.js
  client/js/screens/Profile/ProfileContainer.js
  client/js/screens/SignIn/SignIn.js
  client/js/screens/SignUp/SignUp.js
  client/js/screens/Store/Store.js
  client/js/screens/Store/StoreContainer.js
  client/js/screens/StoresBrands/StoresBrands.js
  client/js/screens/StoresBrands/StoresBrandsContainer.js
Labels: enhancement

#58 Vs feature foryou screen
  client/js/App.js
  client/js/assets/activeheart.png
  client/js/components/ImageCarousel/ImageCarousel.js
  client/js/components/ImageCarousel/styles.js
  client/js/components/ItemList/ItemList.js
  client/js/components/ItemList/styles.js
  client/js/navigation/NavigationLayout.js
  client/js/screens/ForYou/ForYou.js
  client/js/screens/ForYou/ForYouContainer.js
  client/js/screens/ForYou/styles.js
  client/js/screens/Item/Item.js
  client/js/screens/Item/ItemContainer.js
  client/js/screens/Profile/Profile.js
Labels: enhancement

#59 Ad feature storebrandlist
  client/js/assets/icons/forward-inactive2x.png
  client/js/assets/icons/partner-active3x.png
  client/js/components/StoreCard/StoreCard.js
  client/js/components/StoreCard/styles.js
  client/js/screens/Brands/Brands.js
  client/js/screens/Brands/BrandsContainer.js
  client/js/screens/Brands/index.js
  client/js/screens/Brands/styles.js
  client/js/screens/ItemsPage/ItemsPageContainer.js
  client/js/screens/StoresBrands/StoresBrands.js
  client/js/screens/StoresBrands/StoresBrandsContainer.js
  client/js/screens/StoresBrands/styles.js
Labels: enhancement

#60 Vs forsalescreen
  client/index.js
  client/js/components/ImageCarousel/ImageCarousel.js
  client/js/components/ItemList/ItemList.js
  client/js/components/ItemStoreCard/ItemStoreCard.js
  client/js/components/ItemStoreCard/styles.js
  client/js/components/StoreCard/StoreCard.js
  client/js/components/StoreCard/styles.js
  client/js/navigation/NavigationLayout.js
  client/js/screens/Brand/Brand.js
  client/js/screens/Item/Item.js
  client/js/screens/ItemsPage/ItemsPageContainer.js
  client/js/screens/Profile/Profile.js
  client/js/screens/Profile/ProfileContainer.js
  client/js/screens/Sale/Sale.js
  client/js/screens/Sale/SaleContainer.js
  client/js/screens/Sale/styles.js
  client/js/screens/SignIn/SignIn.js
  client/js/screens/SignUp/SignUp.js
  client/js/screens/Store/Store.js
  server/types.graphql
Labels: bug, enhancement

#55 Yy feature create react native tab view for profile pafe
  client/js/App.js
  client/js/assets/active.png
  client/js/assets/inactive.png
  client/js/assets/profilepic.png
  client/js/components/Faves/FavesContainer.js
  client/js/components/TabViewProfile/TabViewProfile.js
  client/js/components/TabViewProfile/index.js
  client/js/components/TabViewProfile/styles.js
  client/js/components/faves/faves.js
  client/js/components/faves/index.js
  client/js/components/faves/styles.js
  client/js/context/FaveItemsContext/FaveItemsContext.js
  client/js/screens/Browse/styles.js
  client/js/screens/Profile/Profile.js
  client/js/screens/Profile/ProfileContainer.js
  client/js/screens/Profile/styles.js
  client/package.json
Labels: enhancement

#70 implement settingsscreen and functionality
  client/js/assets/icons/inactive.png
  client/js/navigation/NavigationLayout.js
  client/js/navigation/config.js
  client/js/navigation/styles.js
  client/js/screens/Settings/Settings.js
  client/js/screens/Settings/SettingsContainer.js
  client/js/screens/Settings/index.js
  client/js/screens/Settings/styles.js
Labels: enhancement

#68 Update brandLogo field in schema
  server/types.graphql
Labels: enhancement

#74 Yy feature refactorbrowsescreen dry
  client/js/components/BrowseItem/BrowseItem.js
  client/js/components/BrowseItem/index.js
  client/js/components/BrowseItem/styles.js
  client/js/config/BrowseItemData.js
  client/js/screens/Browse/Browse.js
  client/js/screens/Browse/BrowseContainer.js
Labels: enhancement

#82 readme writeup
  README.md
Labels: enhancement

#81 fix for you page query
  client/js/screens/ForYou/ForYouContainer.js
Labels: bug

#91 Vs feature foryouscreenbugs
  client/js/navigation/styles.js
  client/js/screens/Brand/Brand.js
  client/js/screens/ForYou/ForYou.js
  client/js/screens/ForYou/styles.js
  client/js/screens/SignIn/SignIn.js
Labels: bug

#89 Ad feature mapmarker
  .gitignore
  client/babel.config.js
  client/js/assets/icons/location-marker3x.png
  client/js/assets/icons/stc-inactive3x.png
  client/js/components/ImageCarousel/styles.js
  client/js/components/ItemStoreCard/ItemStoreCard.js
  client/js/components/StoreCard/StoreCard.js
  client/js/components/StoreCard/styles.js
  client/js/config/geocode-api.js
  client/js/navigation/NavigationLayout.js
  client/js/screens/Brand/Brand.js
  client/js/screens/Brand/styles.js
  client/js/screens/BrandItems/BrandItems.js
  client/js/screens/BrandItems/BrandItemsContainer.js
  client/js/screens/BrandItems/index.js
  client/js/screens/BrandItems/styles.js
  client/js/screens/Map/Map.js
  client/js/screens/Map/MapContainer.js
  client/js/screens/Map/index.js
  client/js/screens/Store/Store.js
  client/js/screens/Store/styles.js
  client/js/screens/StoresBrands/StoresBrandsContainer.js
  client/package.json
  client/yarn.lock
Labels: enhancement

#93 Yy feature gravatar
  client/js/screens/Profile/Profile.js
  client/js/screens/Profile/styles.js
Labels: Epic, enhancement

#97 Vs feature new filter
  client/ios/STCSummer2019.xcodeproj/project.pbxproj
  client/ios/STCSummer2019/Images.xcassets/SplashIcon.imageset/Contents.json
  client/js/assets/icons/checkmark.png
  client/js/components/Filter/Filter.js
  client/js/components/Filter/index.js
  client/js/components/FilterList/FilterList.js
  client/js/components/FilterList/index.js
  client/js/components/FilterList/styles.js
  client/js/components/FilterModal/FilterModal.js
  client/js/components/FilterModal/index.js
  client/js/config/BrowseItemData.js
  client/js/screens/ForYou/ForYou.js
  client/js/screens/ForYou/ForYouContainer.js
  client/js/screens/ItemsPage/ItemsPage.js
  client/package.json
  client/yarn.lock
  server/types.graphql
Labels: enhancement

#90 Sd feature clean up
  client/js/assets/icons/active.png
  client/js/assets/icons/activefilter.png
  client/js/assets/icons/activeheart.png
  client/js/assets/icons/dropdown.png
  client/js/assets/icons/inactivefilter.png
  client/js/assets/icons/inactiveheart.png
  client/js/assets/icons/logo.png
  client/js/assets/icons/profilepic.png
  client/js/assets/inactive.png
  client/js/components/ImageCarousel/ImageCarousel.js
  client/js/components/ItemList/ItemList.js
  client/js/components/ItemList/styles.js
  client/js/components/ItemStoreCard/ItemStoreCard.js
  client/js/components/Loader/Loader.js
  client/js/components/PhotoTab/PhotoTab.js
  client/js/config/BrowseItemData.js
  client/js/screens/BrandItems/BrandItems.js
  client/js/screens/Browse/Browse.js
  client/js/screens/ForYou/ForYou.js
  client/js/screens/ItemsPage/ItemsPage.js
  client/js/screens/Profile/Profile.js
  client/js/screens/SignIn/SignIn.js
  client/js/screens/SignUp/SignUp.js
  client/package.json
  client/yarn.lock
Labels: enhancement

#95 Yy feature fixsettingspage
  client/js/config/BrowseItemData.js
  client/js/navigation/styles.js
  client/js/screens/Settings/Settings.js
  client/js/screens/Settings/styles.js
Labels: enhancement

#99 fix profile page image not clickable issue, fix settings page onboard…
  client/ios/STCSummer2019/Info.plist
  client/js/components/BrandTab/BrandTab.js
  client/js/components/BrandTab/styles.js
  client/js/components/FilterItemList/FilterItemList.js
  client/js/components/FilterItemList/index.js
  client/js/components/FilterItemList/styles.js
  client/js/components/ItemStoreCard/ItemStoreCard.js
  client/js/components/ItemStoreCard/styles.js
  client/js/components/ItemTab/ItemTab.js
  client/js/components/StoreTab/StoreTab.js
  client/js/components/StoreTab/styles.js
  client/js/navigation/NavigationLayout.js
  client/js/navigation/RootStackNavigator.js
  client/js/navigation/config.js
  client/js/screens/Brand/BrandContainer.js
  client/js/screens/Filter/Filter.js
  client/js/screens/Filter/FilterContainer.js
  client/js/screens/Filter/index.js
  client/js/screens/Filter/styles.js
  client/js/screens/ForYou/ForYouContainer.js
  client/js/screens/OnBoarding/OnBoarding.js
  client/js/screens/Settings/Settings.js
Labels: bug

#104 Vs feature filterfix
  client/js/components/Filter/Filter.js
  client/js/components/FilterList/FilterList.js
  client/js/components/FilterModal/FilterModal.js
  client/js/components/StoreTab/styles.js
  client/js/config/models/onBoarding.js
  client/js/navigation/NavigationLayout.js
  client/js/screens/AuthLoading/AuthLoading.js
  client/js/screens/OnBoarding/OnBoarding.js
  client/js/screens/Profile/Profile.js
  client/js/screens/Settings/Settings.js
Labels: enhancement

#103 Sd feature clean up
  README.md
  client/js/components/FilterModal/FilterModal.js
  client/js/components/FilterModal/styles.js
  client/js/screens/BrandItems/BrandItems.js
Labels: enhancement

#107 Vs feature bugfix
  client/ios/STCSummer2019/Images.xcassets/AppIcon.appiconset/Contents.json
  client/ios/STCSummer2019/Images.xcassets/AppIcon.appiconset/app-logo@2x.png
  client/ios/STCSummer2019/Images.xcassets/AppIcon.appiconset/app-logo@3x.png
  client/ios/STCSummer2019/Images.xcassets/AppIcon.appiconset/appicon@2x.png
  client/ios/STCSummer2019/Images.xcassets/AppIcon.appiconset/appicon@3x.png
  client/js/components/BrandTab/BrandTab.js
  client/js/components/ImageCarousel/ImageCarousel.js
  client/js/components/StoreTab/StoreTab.js
  client/js/components/StoreTab/styles.js
  client/js/components/TabProfile/styles.js
  client/js/navigation/NavigationLayout.js
  client/js/screens/BrandItems/BrandItemsContainer.js
  client/js/screens/Browse/BrowseContainer.js
  client/js/screens/ForYou/ForYou.js
  client/js/screens/ForYou/ForYouContainer.js
  client/js/screens/OnBoarding/OnBoarding.js
  client/js/screens/OnBoarding/OnBoardingContainer.js
  client/js/screens/OnBoarding/index.js
  client/js/screens/Profile/ProfileContainer.js
  client/js/screens/Settings/Settings.js
  client/js/screens/SignUp/SignUp.js
Labels: bug

#108 Sd feature clean up
  README.md
  client/js/components/Filter/Filter.js
  client/js/components/FilterList/FilterList.js
  client/js/components/FilterList/styles.js
  client/js/components/ImageCarousel/styles.js
  client/js/navigation/NavigationLayout.js
  client/js/screens/AuthLoading/AuthLoading.js
  client/js/screens/OnBoarding/OnBoarding.js
  client/js/screens/Sale/styles.js
  client/js/screens/Settings/Settings.js
Labels: enhancement

#112 Ad feature stylefix
  client/index.js
  client/js/components/ImageCarousel/ImageCarousel.js
  client/js/components/ImageCarousel/styles.js
  client/js/screens/Browse/styles.js
Labels: enhancement
